//
// `handle-cmd.ts`
//
// Documention:
// - just-bash: https://github.com/vercel-labs/just-bash/blob/main/packages/just-bash/README.md#supported-commands
//              https://www.npmjs.com/package/just-bash
//
// Illustrate:
// Support for virtual BusyBox commands,
// such as `cat`, `ls`, and `cd`, including some custom commands.
//
// Class:
// - DefineCommandOutput: Define terminal commands. {
//   termIO: Includes standard output, error messages,
//           and the command execution return value.
//           { stdout, stderr, exitCode }
//   getCmd: Hand the command over to the just-bash module for processing.
//   handleHello: Display "hello" in the terminal when the user says hello.
// }
//
// Functions:
// - handleCommand: When a user enters a command in the terminal,
//                  the input is passed to the `Bash` process;
//                  the output is then retrieved via `response.stdout`,
//                  with extra newline characters removed to prevent formatting issues.
//

import type { Terminal } from "@xterm/xterm";
import { Bash, defineCommand } from "just-bash";
import { pipeline } from "@huggingface/transformers";

/**
 * @file Frontend virtual file system
 * @see {
 *   @link https://docs.kernel.org/filesystems/index.html
 * }
 */
import { virtualFS } from "./vir-filesystem.ts";

interface TextGenerationOutput {
  generated_text: string;
}

class DefineCommandOutput {
  /**
   * Standard input, output and return values.
   *
   * @example
   * this.termIO.stdout = "This is output message."
   * this.termIO.stderr = "This is error message."
   * this.termIO.exitCode = "0" - success
   */
  public termIO = {
    stdout: "[info]",
    stderr: "",
    exitCode: 0,
  };

  public handleHello(args: string[]) {
    /**
     * @deprecated
     * NOTE: This is test command, will be removed in the future.
     */
    return {
      stdout: this.termIO.stdout + "hello" + " " + args.join(" "),
      stderr: this.termIO.stderr,
      exitCode: this.termIO.exitCode,
    };
  }

  public async handleNaturalSearch(args: string[]) {
    /**
     * Text information is generated by inferring from fuzzy information
     * using a lightweight local large model.
     *
     * @see {
     *   @link 'https://www.npmjs.com/package/@huggingface/transformers'
     *   @link https://huggingface.co/docs/transformers.js/main/en/api/pipelines#module_pipelines.Text2TextGenerationPipeline
     * }
     */

    const naturalLangSearchStatus = localStorage.getItem(
      "enabled_local_natural_language_search",
    );

    /**
     * Local large model switch (if enabled by default, it will consume
     * storage space and slow down the terminal response speed).
     *
     * @default disabled
     * @example `natural-lang --open` (bash terminal)
     */
    if (args[0] === "--open") {
      if (!naturalLangSearchStatus) {
        localStorage.setItem(
          "enabled_local_natural_language_search",
          "enabled",
        );
        return {
          stdout: "Emmmm... Downloading models needs take a while.",
          stderr: "",
          exitCode: 0,
        };
      } else if (typeof naturalLangSearchStatus !== "string") {
        return { stdout: "Emmmm.....", stderr: "", exitCode: 1 };
      }
    }

    /**
     * @param naturalLangSearchStatus - Save model switch state.
     */
    if (naturalLangSearchStatus === "enabled") {
      const generator = await pipeline(
        "text2text-generation",
        "Xenova/LaMini-Flan-T5-783M",
      );

      /**
       * Generate text content based on the model.
       * @bug It seems that you cannot directly assign a value
       *      using the form `const outputa = output.b`. (fixed)
       * @workaround The current compromise is to use `const genOutput = JSON.stringify(output)` to convert the
       *             data to a string and then print it directly.
       * @note When using `console.log(output)`, it returns type Array.
       *
       * @constant { Array }
       */
      const output = await generator("how can I become more healthy?", {
        max_new_tokens: 100,
      });

      /**
       * To solve this problem, first define an object named `TextGenerationOutput` in
       * the file header, then define the type of the variable `genOutput` as string, and
       * return an empty string if `result[0]?.generated_text` has no result.
       *
       * @example `console.log(output)`
       *          `const genOutput = JSON.stringify(output)`
       */
      const result = output as TextGenerationOutput[];
      const genOutput: string = result[0]?.generated_text ?? "";
      return {
        stdout: genOutput,
        stderr: this.termIO.stderr,
        exitCode: this.termIO.exitCode,
      };
    }

    return {
      stdout: this.termIO.stdout,
      stderr: this.termIO.stderr,
      exitCode: this.termIO.exitCode,
    };
  }

  public getCmd() {
    /**
     * Instantiate a written function.
     * Use the `dfo.getCmd()` function to delegate execution to just-bash.
     *
     * @see {
     *   @link https://github.com/vercel-labs/just-bash/blob/main/packages/just-bash/README.md#custom-commands
     *   @example
     *   ```typescript
     *   const hello = defineCommand("hello", async (args, ctx) => {
     *    const name = args[0] || "world";
     *    return { stdout: `Hello, ${name}!\n`, stderr: "", exitCode: 0 };
     *   });
     *   await bash.exec("hello Alice"); // "Hello, Alice!\n"
     *   ```
     * }
     */
    return [
      defineCommand("hello", (args) => Promise.resolve(this.handleHello(args))),
      defineCommand("natural-lang", (args) =>
        Promise.resolve(this.handleNaturalSearch(args)),
      ),
    ];
  }
}

const dfo = new DefineCommandOutput();
export async function handleCommand(cmdline: string, term: Terminal) {
  /**
   * @summary Initialize the executable command envirorment.
   * @param customCommands - Custom executable commands.
   * @param files - Virtual File System.
   */
  const bash = new Bash({
    customCommands: dfo.getCmd(),
    /**
     * @example
     * files: {
     *   "1.txt": "This is 1.txt.",
     *   "2.txt": "This is 2.txt.",
     *   "3.txt": "This is 3.txt.",
     * },
     */
    files: virtualFS,
  });

  /**
   * @summary Remove extra spaces and line breaks.
   */
  if (!cmdline.trim()) return;
  const response = await bash.exec(cmdline);
  if (response.stdout) {
    term.write(response.stdout.replace(/\r?\n/g, "\r\n"));
  }
  if (response.stderr) {
    term.write(response.stderr.replace(/\r?\n/g, "\r\n"));
  }
}
