#!/bin/bash
echo "[Check] Git push code strict check"
git diff-tree --no-commit-id --name-only -r HEAD | grep -E '\.(ts|tsx|js|jsx)$' | xargs pnpm lint

STATUS=$?

if [ $STATUS -ne 0 ]; then
    exit 1
fi

echo "[Passed] Congratulations! Check passed!"
