/**
 * Text information is generated by inferring from fuzzy information
 * using a lightweight local large model.
 *
 * @see {
 *   @link 'https://www.npmjs.com/package/@huggingface/transformers'
 *   @link https://huggingface.co/docs/transformers.js/main/en/api/pipelines#module_pipelines.Text2TextGenerationPipeline
 * }
 */

interface TextGenerationOutput {
  generated_text: string;
}

/**
 * @param naturalLangSearchStatus - Save model switch state.
 */
const naturalLangSearchStatus = localStorage.getItem(
  "enabled_local_natural_language_search",
);

async function generatedText() {
  const { pipeline } = await import("@huggingface/transformers");
  const generator = await pipeline(
    "text2text-generation",
    "Xenova/LaMini-Flan-T5-783M",
  );

  /**
   * Generate text content based on the model.
   * @bug It seems that you cannot directly assign a value
   *      using the form `const outputa = output.b`. (fixed)
   * @workaround The current compromise is to use `const genOutput = JSON.stringify(output)` to convert the
   *             data to a string and then print it directly.
   * @note When using `console.log(output)`, it returns type Array.
   *
   * @constant { Array }
   */
  const output = await generator("how can I become more healthy?", {
    max_new_tokens: 100,
  });

  /**
   * To solve this problem, first define an object named `TextGenerationOutput` in
   * the file header, then define the type of the variable `genOutput` as string, and
   * return an empty string if `result[0]?.generated_text` has no result.
   *
   * @example `console.log(output)`
   *          `const genOutput = JSON.stringify(output)`
   */
  const result = output as TextGenerationOutput[];
  const genOutput = result[0]?.generated_text ?? "";
  return genOutput;
}

export async function getNaturalOutput() {
  try {
    const transformers = await import("@huggingface/transformers");
    if (
      !transformers ||
      typeof transformers.pipeline !== "function" ||
      naturalLangSearchStatus
    ) {
      console.warn("Missing function: pipeline, on transformers module.");
      return "";
    }
    return await generatedText();
  } catch (error) {
    console.warn(
      "You should install transformers to enable local natural language feature.",
      error,
    );
    return "";
  }
}
